# Generated by Django 4.2.2 on 2023-06-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ddffdfs', upload_to='pics'),
            preserve_default=False,
        ),
    ]
